#!/usr/bin/env python3
"""
Sample Python script generated by Vikas Coding Editor Social
"""

def main():
    print("Welcome to the Python Script!")
    print("=" * 40)
    
    # Get user input
    name = input("Enter your name: ")
    
    if name:
        print(f"Hello, {name}! Welcome to the project.")
    else:
        print("Hello, anonymous user!")
    
    # Simple calculation example
    try:
        num1 = float(input("Enter a number: "))
        num2 = float(input("Enter another number: "))
        
        print(f"\nResults:")
        print(f"{num1} + {num2} = {num1 + num2}")
        print(f"{num1} - {num2} = {num1 - num2}")
        print(f"{num1} * {num2} = {num1 * num2}")
        
        if num2 != 0:
            print(f"{num1} / {num2} = {num1 / num2}")
        else:
            print("Cannot divide by zero!")
            
    except ValueError:
        print("Please enter valid numbers!")

if __name__ == "__main__":
    main()